[challenge]
name = "included"
points = 500
files = ["src.tar.gz"]
flag = "gigem{s1mpl3_lfi_vuln}"

[docker]
build = "-t included ."
run = "-d --read-only --restart=always --cpus=1 --memory=32m"

[service]
sni = "included"
port = 9004

[nginx]
type = "site"
balance-method = "ip_hash"
instances = 5
