[challenge]
name = "filters"
points = 500
files = ["src/index.php"]
flag = "gigem{l3ss_s1mpl3_lfi_vuln_0xd34db33f}"

[docker]
build = "-t filters ."
run = "-d --read-only --restart=always --cpus=1 --memory=32m"

[service]
sni = "filters"
port = 9003

[nginx]
type = "site"
balance-method = "ip_hash"
instances = 5
