[challenge]
name = "blocked"
points = 500
files = []
flag = "gigem{n0t_th3_m0st_s3cur3_auth_m34sure}"

[docker]
build = "-t blocked ."
run = "-d --read-only --restart=always --cpus=1 --memory=32m"

[service]
sni = "blocked"
port = 9001

[nginx]
type = "site"
balance-method = "ip_hash"
instances = 5
