[challenge]
name = "rsa_oops"
points = 500
files = []
flag = "gigem{r54_15_h0m0m0rph1c}"

[docker]
build = "-t pwn_warmup --build-arg name=pwn_warmup --build-arg port=8000 ."
run = "-d --restart=always --cpus=1 --memory=32m"

[service]
sni = "rsa_oops"
port = 8000

[nginx]
type = "stream"
balance-method = "least_conn"
instances = 5
